/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.customercare.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AgentDataEntry service. Represents a row in the &quot;CC_AgentDataEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.customercare.model.impl.AgentDataEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.customercare.model.impl.AgentDataEntryImpl}.
 * </p>
 *
 * @author DuyMB
 * @see AgentDataEntry
 * @see com.liferay.docs.customercare.model.impl.AgentDataEntryImpl
 * @see com.liferay.docs.customercare.model.impl.AgentDataEntryModelImpl
 * @generated
 */
public interface AgentDataEntryModel extends BaseModel<AgentDataEntry>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agent data entry model instance should use the {@link AgentDataEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this agent data entry.
	 *
	 * @return the primary key of this agent data entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agent data entry.
	 *
	 * @param primaryKey the primary key of this agent data entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agent data entry ID of this agent data entry.
	 *
	 * @return the agent data entry ID of this agent data entry
	 */
	public long getAgentDataEntryId();

	/**
	 * Sets the agent data entry ID of this agent data entry.
	 *
	 * @param agentDataEntryId the agent data entry ID of this agent data entry
	 */
	public void setAgentDataEntryId(long agentDataEntryId);

	/**
	 * Returns the group ID of this agent data entry.
	 *
	 * @return the group ID of this agent data entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this agent data entry.
	 *
	 * @param groupId the group ID of this agent data entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this agent data entry.
	 *
	 * @return the company ID of this agent data entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this agent data entry.
	 *
	 * @param companyId the company ID of this agent data entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this agent data entry.
	 *
	 * @return the user ID of this agent data entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this agent data entry.
	 *
	 * @param userId the user ID of this agent data entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this agent data entry.
	 *
	 * @return the user uuid of this agent data entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this agent data entry.
	 *
	 * @param userUuid the user uuid of this agent data entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this agent data entry.
	 *
	 * @return the user name of this agent data entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this agent data entry.
	 *
	 * @param userName the user name of this agent data entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this agent data entry.
	 *
	 * @return the create date of this agent data entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this agent data entry.
	 *
	 * @param createDate the create date of this agent data entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agent data entry.
	 *
	 * @return the modified date of this agent data entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agent data entry.
	 *
	 * @param modifiedDate the modified date of this agent data entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the agent ID of this agent data entry.
	 *
	 * @return the agent ID of this agent data entry
	 */
	public long getAgentId();

	/**
	 * Sets the agent ID of this agent data entry.
	 *
	 * @param agentId the agent ID of this agent data entry
	 */
	public void setAgentId(long agentId);

	/**
	 * Returns the queue list of this agent data entry.
	 *
	 * @return the queue list of this agent data entry
	 */
	@AutoEscape
	public String getQueueList();

	/**
	 * Sets the queue list of this agent data entry.
	 *
	 * @param queueList the queue list of this agent data entry
	 */
	public void setQueueList(String queueList);

	/**
	 * Returns the extension of this agent data entry.
	 *
	 * @return the extension of this agent data entry
	 */
	@AutoEscape
	public String getExtension();

	/**
	 * Sets the extension of this agent data entry.
	 *
	 * @param extension the extension of this agent data entry
	 */
	public void setExtension(String extension);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.docs.customercare.model.AgentDataEntry agentDataEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.docs.customercare.model.AgentDataEntry> toCacheModel();

	@Override
	public com.liferay.docs.customercare.model.AgentDataEntry toEscapedModel();

	@Override
	public com.liferay.docs.customercare.model.AgentDataEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}