/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.customercare.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CallDataEntry service. Represents a row in the &quot;CC_CallDataEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.customercare.model.impl.CallDataEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.customercare.model.impl.CallDataEntryImpl}.
 * </p>
 *
 * @author DuyMB
 * @see CallDataEntry
 * @see com.liferay.docs.customercare.model.impl.CallDataEntryImpl
 * @see com.liferay.docs.customercare.model.impl.CallDataEntryModelImpl
 * @generated
 */
public interface CallDataEntryModel extends BaseModel<CallDataEntry>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a call data entry model instance should use the {@link CallDataEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this call data entry.
	 *
	 * @return the primary key of this call data entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this call data entry.
	 *
	 * @param primaryKey the primary key of this call data entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the call data entry ID of this call data entry.
	 *
	 * @return the call data entry ID of this call data entry
	 */
	public long getCallDataEntryId();

	/**
	 * Sets the call data entry ID of this call data entry.
	 *
	 * @param callDataEntryId the call data entry ID of this call data entry
	 */
	public void setCallDataEntryId(long callDataEntryId);

	/**
	 * Returns the group ID of this call data entry.
	 *
	 * @return the group ID of this call data entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this call data entry.
	 *
	 * @param groupId the group ID of this call data entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this call data entry.
	 *
	 * @return the company ID of this call data entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this call data entry.
	 *
	 * @param companyId the company ID of this call data entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this call data entry.
	 *
	 * @return the user ID of this call data entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this call data entry.
	 *
	 * @param userId the user ID of this call data entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this call data entry.
	 *
	 * @return the user uuid of this call data entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this call data entry.
	 *
	 * @param userUuid the user uuid of this call data entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this call data entry.
	 *
	 * @return the user name of this call data entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this call data entry.
	 *
	 * @param userName the user name of this call data entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this call data entry.
	 *
	 * @return the create date of this call data entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this call data entry.
	 *
	 * @param createDate the create date of this call data entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this call data entry.
	 *
	 * @return the modified date of this call data entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this call data entry.
	 *
	 * @param modifiedDate the modified date of this call data entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the call ID of this call data entry.
	 *
	 * @return the call ID of this call data entry
	 */
	@AutoEscape
	public String getCallId();

	/**
	 * Sets the call ID of this call data entry.
	 *
	 * @param callId the call ID of this call data entry
	 */
	public void setCallId(String callId);

	/**
	 * Returns the start call date of this call data entry.
	 *
	 * @return the start call date of this call data entry
	 */
	public Date getStartCallDate();

	/**
	 * Sets the start call date of this call data entry.
	 *
	 * @param startCallDate the start call date of this call data entry
	 */
	public void setStartCallDate(Date startCallDate);

	/**
	 * Returns the end call date of this call data entry.
	 *
	 * @return the end call date of this call data entry
	 */
	public Date getEndCallDate();

	/**
	 * Sets the end call date of this call data entry.
	 *
	 * @param endCallDate the end call date of this call data entry
	 */
	public void setEndCallDate(Date endCallDate);

	/**
	 * Returns the queue name of this call data entry.
	 *
	 * @return the queue name of this call data entry
	 */
	@AutoEscape
	public String getQueueName();

	/**
	 * Sets the queue name of this call data entry.
	 *
	 * @param queueName the queue name of this call data entry
	 */
	public void setQueueName(String queueName);

	/**
	 * Returns the call number of this call data entry.
	 *
	 * @return the call number of this call data entry
	 */
	@AutoEscape
	public String getCallNumber();

	/**
	 * Sets the call number of this call data entry.
	 *
	 * @param callNumber the call number of this call data entry
	 */
	public void setCallNumber(String callNumber);

	/**
	 * Returns the channel of this call data entry.
	 *
	 * @return the channel of this call data entry
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this call data entry.
	 *
	 * @param channel the channel of this call data entry
	 */
	public void setChannel(String channel);

	/**
	 * Returns the wait time of this call data entry.
	 *
	 * @return the wait time of this call data entry
	 */
	@AutoEscape
	public String getWaitTime();

	/**
	 * Sets the wait time of this call data entry.
	 *
	 * @param waitTime the wait time of this call data entry
	 */
	public void setWaitTime(String waitTime);

	/**
	 * Returns the duration time of this call data entry.
	 *
	 * @return the duration time of this call data entry
	 */
	@AutoEscape
	public String getDurationTime();

	/**
	 * Sets the duration time of this call data entry.
	 *
	 * @param durationTime the duration time of this call data entry
	 */
	public void setDurationTime(String durationTime);

	/**
	 * Returns the extension of this call data entry.
	 *
	 * @return the extension of this call data entry
	 */
	@AutoEscape
	public String getExtension();

	/**
	 * Sets the extension of this call data entry.
	 *
	 * @param extension the extension of this call data entry
	 */
	public void setExtension(String extension);

	/**
	 * Returns the status of this call data entry.
	 *
	 * @return the status of this call data entry
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this call data entry.
	 *
	 * @param status the status of this call data entry
	 */
	public void setStatus(String status);

	/**
	 * Returns the channel old of this call data entry.
	 *
	 * @return the channel old of this call data entry
	 */
	@AutoEscape
	public String getChannelOld();

	/**
	 * Sets the channel old of this call data entry.
	 *
	 * @param channelOld the channel old of this call data entry
	 */
	public void setChannelOld(String channelOld);

	/**
	 * Returns the channel to of this call data entry.
	 *
	 * @return the channel to of this call data entry
	 */
	@AutoEscape
	public String getChannelTo();

	/**
	 * Sets the channel to of this call data entry.
	 *
	 * @param channelTo the channel to of this call data entry
	 */
	public void setChannelTo(String channelTo);

	/**
	 * Returns the ext of monitor of this call data entry.
	 *
	 * @return the ext of monitor of this call data entry
	 */
	@AutoEscape
	public String getExtOfMonitor();

	/**
	 * Sets the ext of monitor of this call data entry.
	 *
	 * @param extOfMonitor the ext of monitor of this call data entry
	 */
	public void setExtOfMonitor(String extOfMonitor);

	/**
	 * Returns the cause code of this call data entry.
	 *
	 * @return the cause code of this call data entry
	 */
	@AutoEscape
	public String getCauseCode();

	/**
	 * Sets the cause code of this call data entry.
	 *
	 * @param causeCode the cause code of this call data entry
	 */
	public void setCauseCode(String causeCode);

	/**
	 * Returns the sip cause of this call data entry.
	 *
	 * @return the sip cause of this call data entry
	 */
	@AutoEscape
	public String getSipCause();

	/**
	 * Sets the sip cause of this call data entry.
	 *
	 * @param sipCause the sip cause of this call data entry
	 */
	public void setSipCause(String sipCause);

	/**
	 * Returns the staff name of this call data entry.
	 *
	 * @return the staff name of this call data entry
	 */
	@AutoEscape
	public String getStaffName();

	/**
	 * Sets the staff name of this call data entry.
	 *
	 * @param staffName the staff name of this call data entry
	 */
	public void setStaffName(String staffName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.docs.customercare.model.CallDataEntry callDataEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.docs.customercare.model.CallDataEntry> toCacheModel();

	@Override
	public com.liferay.docs.customercare.model.CallDataEntry toEscapedModel();

	@Override
	public com.liferay.docs.customercare.model.CallDataEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}