/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.customercare.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CustomerInforEntry service. Represents a row in the &quot;CC_CustomerInforEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.customercare.model.impl.CustomerInforEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.customercare.model.impl.CustomerInforEntryImpl}.
 * </p>
 *
 * @author DuyMB
 * @see CustomerInforEntry
 * @see com.liferay.docs.customercare.model.impl.CustomerInforEntryImpl
 * @see com.liferay.docs.customercare.model.impl.CustomerInforEntryModelImpl
 * @generated
 */
public interface CustomerInforEntryModel extends BaseModel<CustomerInforEntry>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer infor entry model instance should use the {@link CustomerInforEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this customer infor entry.
	 *
	 * @return the primary key of this customer infor entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer infor entry.
	 *
	 * @param primaryKey the primary key of this customer infor entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the customer infor entry ID of this customer infor entry.
	 *
	 * @return the customer infor entry ID of this customer infor entry
	 */
	public long getCustomerInforEntryId();

	/**
	 * Sets the customer infor entry ID of this customer infor entry.
	 *
	 * @param customerInforEntryId the customer infor entry ID of this customer infor entry
	 */
	public void setCustomerInforEntryId(long customerInforEntryId);

	/**
	 * Returns the group ID of this customer infor entry.
	 *
	 * @return the group ID of this customer infor entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this customer infor entry.
	 *
	 * @param groupId the group ID of this customer infor entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this customer infor entry.
	 *
	 * @return the company ID of this customer infor entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this customer infor entry.
	 *
	 * @param companyId the company ID of this customer infor entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this customer infor entry.
	 *
	 * @return the user ID of this customer infor entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this customer infor entry.
	 *
	 * @param userId the user ID of this customer infor entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this customer infor entry.
	 *
	 * @return the user uuid of this customer infor entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this customer infor entry.
	 *
	 * @param userUuid the user uuid of this customer infor entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this customer infor entry.
	 *
	 * @return the user name of this customer infor entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this customer infor entry.
	 *
	 * @param userName the user name of this customer infor entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this customer infor entry.
	 *
	 * @return the create date of this customer infor entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this customer infor entry.
	 *
	 * @param createDate the create date of this customer infor entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this customer infor entry.
	 *
	 * @return the modified date of this customer infor entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this customer infor entry.
	 *
	 * @param modifiedDate the modified date of this customer infor entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the cust name of this customer infor entry.
	 *
	 * @return the cust name of this customer infor entry
	 */
	@AutoEscape
	public String getCustName();

	/**
	 * Sets the cust name of this customer infor entry.
	 *
	 * @param custName the cust name of this customer infor entry
	 */
	public void setCustName(String custName);

	/**
	 * Returns the cust identiication of this customer infor entry.
	 *
	 * @return the cust identiication of this customer infor entry
	 */
	@AutoEscape
	public String getCustIdentiication();

	/**
	 * Sets the cust identiication of this customer infor entry.
	 *
	 * @param custIdentiication the cust identiication of this customer infor entry
	 */
	public void setCustIdentiication(String custIdentiication);

	/**
	 * Returns the phone number of this customer infor entry.
	 *
	 * @return the phone number of this customer infor entry
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this customer infor entry.
	 *
	 * @param phoneNumber the phone number of this customer infor entry
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the address of this customer infor entry.
	 *
	 * @return the address of this customer infor entry
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this customer infor entry.
	 *
	 * @param address the address of this customer infor entry
	 */
	public void setAddress(String address);

	/**
	 * Returns the service of this customer infor entry.
	 *
	 * @return the service of this customer infor entry
	 */
	@AutoEscape
	public String getService();

	/**
	 * Sets the service of this customer infor entry.
	 *
	 * @param service the service of this customer infor entry
	 */
	public void setService(String service);

	/**
	 * Returns the comment of this customer infor entry.
	 *
	 * @return the comment of this customer infor entry
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this customer infor entry.
	 *
	 * @param comment the comment of this customer infor entry
	 */
	public void setComment(String comment);

	/**
	 * Returns the status of this customer infor entry.
	 *
	 * @return the status of this customer infor entry
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this customer infor entry.
	 *
	 * @param status the status of this customer infor entry
	 */
	public void setStatus(String status);

	/**
	 * Returns the reason of this customer infor entry.
	 *
	 * @return the reason of this customer infor entry
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this customer infor entry.
	 *
	 * @param reason the reason of this customer infor entry
	 */
	public void setReason(String reason);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.docs.customercare.model.CustomerInforEntry customerInforEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.docs.customercare.model.CustomerInforEntry> toCacheModel();

	@Override
	public com.liferay.docs.customercare.model.CustomerInforEntry toEscapedModel();

	@Override
	public com.liferay.docs.customercare.model.CustomerInforEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}