/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.customercare.model.impl;

import com.liferay.docs.customercare.model.AgentDataEntry;
import com.liferay.docs.customercare.service.AgentDataEntryLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the AgentDataEntry service. Represents a row in the &quot;CC_AgentDataEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AgentDataEntryImpl}.
 * </p>
 *
 * @author DuyMB
 * @see AgentDataEntryImpl
 * @see com.liferay.docs.customercare.model.AgentDataEntry
 * @generated
 */
public abstract class AgentDataEntryBaseImpl extends AgentDataEntryModelImpl
	implements AgentDataEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a agent data entry model instance should use the {@link AgentDataEntry} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			AgentDataEntryLocalServiceUtil.addAgentDataEntry(this);
		}
		else {
			AgentDataEntryLocalServiceUtil.updateAgentDataEntry(this);
		}
	}
}